# Generated by Django 4.2.21 on 2025-10-16 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recruitment',
            options={'ordering': ['-posted_on'], 'verbose_name': 'Job Posting', 'verbose_name_plural': 'Job Postings'},
        ),
        migrations.AlterField(
            model_name='recruitment',
            name='apply_link',
            field=models.URLField(help_text='URL to apply for the position', max_length=500),
        ),
        migrations.AlterField(
            model_name='recruitment',
            name='company_name',
            field=models.CharField(help_text='Name of the hiring company', max_length=255),
        ),
        migrations.AlterField(
            model_name='recruitment',
            name='deadline',
            field=models.DateField(help_text='Application deadline'),
        ),
        migrations.AlterField(
            model_name='recruitment',
            name='description',
            field=models.TextField(help_text='Detailed job description'),
        ),
        migrations.AlterField(
            model_name='recruitment',
            name='job_type',
            field=models.CharField(choices=[('FT', 'Full-Time'), ('PT', 'Part-Time'), ('IN', 'Internship')], default='FT', help_text='Type of employment', max_length=2),
        ),
        migrations.AlterField(
            model_name='recruitment',
            name='location',
            field=models.CharField(help_text='Job location', max_length=255),
        ),
        migrations.AlterField(
            model_name='recruitment',
            name='position',
            field=models.CharField(help_text='Job title/position', max_length=255),
        ),
        migrations.AlterField(
            model_name='recruitment',
            name='posted_on',
            field=models.DateTimeField(auto_now_add=True, help_text='When the job was posted'),
        ),
        migrations.AlterField(
            model_name='recruitment',
            name='requirements',
            field=models.TextField(help_text='Required qualifications and skills'),
        ),
        migrations.AlterField(
            model_name='recruitment',
            name='salary',
            field=models.CharField(blank=True, help_text='Salary information', max_length=100, null=True),
        ),
    ]
