# Generated by Django 4.2.21 on 2025-10-16 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0007_alter_subjectmaterial_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='materialtype',
            options={'ordering': ['name'], 'verbose_name': 'Material Type', 'verbose_name_plural': 'Material Types'},
        ),
        migrations.AlterModelOptions(
            name='program',
            options={'ordering': ['name'], 'verbose_name': 'Academic Program', 'verbose_name_plural': 'Academic Programs'},
        ),
        migrations.AlterModelOptions(
            name='syllabus',
            options={'ordering': ['program__short_name', 'name'], 'verbose_name': 'Syllabus', 'verbose_name_plural': 'Syllabi'},
        ),
        migrations.AlterModelOptions(
            name='term',
            options={'ordering': ['syllabus__program__short_name', 'syllabus__name', 'term_number'], 'verbose_name': 'Academic Term', 'verbose_name_plural': 'Academic Terms'},
        ),
        migrations.AlterField(
            model_name='materialtype',
            name='description',
            field=models.TextField(blank=True, help_text='Detailed description'),
        ),
        migrations.AlterField(
            model_name='materialtype',
            name='name',
            field=models.CharField(help_text='Material type name', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='duration_years',
            field=models.PositiveSmallIntegerField(help_text='Program duration in years'),
        ),
        migrations.AlterField(
            model_name='program',
            name='name',
            field=models.CharField(help_text='Full program name', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='short_name',
            field=models.CharField(help_text='Short code for API filtering', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='code',
            field=models.CharField(help_text='Subject code (e.g., BN101)', max_length=50),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(help_text='Full subject name', max_length=255),
        ),
        migrations.AlterField(
            model_name='subjectmaterial',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Upload timestamp'),
        ),
        migrations.AlterField(
            model_name='subjectmaterial',
            name='description',
            field=models.TextField(blank=True, help_text='Additional description'),
        ),
        migrations.AlterField(
            model_name='subjectmaterial',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether material is available'),
        ),
        migrations.AlterField(
            model_name='subjectmaterial',
            name='title',
            field=models.CharField(help_text='Display title (auto-filled from filename)', max_length=255),
        ),
        migrations.AlterField(
            model_name='syllabus',
            name='effective_from',
            field=models.DateField(blank=True, help_text='Effective start date', null=True),
        ),
        migrations.AlterField(
            model_name='syllabus',
            name='effective_to',
            field=models.DateField(blank=True, help_text='Effective end date', null=True),
        ),
        migrations.AlterField(
            model_name='syllabus',
            name='name',
            field=models.CharField(help_text='Syllabus name/version', max_length=255),
        ),
    ]
